### ISSUE TITLE
Pfad bei der Ausführung des Skripts

### ISSUE THREAD

**Issue by karhunenloeve** [karhunenloeve/Shapy#8]
Bei der Ausführung des Skripts wird man aufgefordert den Pfad einzugeben. Diese Angabe ist nicht eindeutig. Absolut vs relativer Pfad? Weiterhin, falls ich den Pfad als String angebe, also mit '' oder "", wird er nicht erkannt. Das sollte man beides mit aufnehmen.

**Comment by Leoturos** [comment]
Wurde gelöst, es funktionieren jetzt sowohl absolute als auch relative Pfade und Anführungszeichen werden ignoriert
